// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: peer.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on WatchUpstreamRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *WatchUpstreamRequest) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// WatchUpstreamRequestValidationError is the validation error returned by
// WatchUpstreamRequest.Validate if the designated constraints aren't met.
type WatchUpstreamRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WatchUpstreamRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WatchUpstreamRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WatchUpstreamRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WatchUpstreamRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WatchUpstreamRequestValidationError) ErrorName() string {
	return "WatchUpstreamRequestValidationError"
}

// Error satisfies the builtin error interface
func (e WatchUpstreamRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWatchUpstreamRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WatchUpstreamRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WatchUpstreamRequestValidationError{}

// Validate checks the field values on WatchUpstreamResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *WatchUpstreamResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// WatchUpstreamResponseValidationError is the validation error returned by
// WatchUpstreamResponse.Validate if the designated constraints aren't met.
type WatchUpstreamResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WatchUpstreamResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WatchUpstreamResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WatchUpstreamResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WatchUpstreamResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WatchUpstreamResponseValidationError) ErrorName() string {
	return "WatchUpstreamResponseValidationError"
}

// Error satisfies the builtin error interface
func (e WatchUpstreamResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWatchUpstreamResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WatchUpstreamResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WatchUpstreamResponseValidationError{}
